name: PullPreview

on:
  pull_request:
    types: [ labeled, unlabeled, synchronize, closed, reopened ]

jobs:
  deploy-staging-environment:
    permissions:
      contents: read # to fetch code (actions/checkout)
      deployments: write # to delete deployments
      pull-requests: write # to remove labels
      statuses: write # to create commit status

    name: Deploy PullPreview staging environment
    uses: cybex-gmbh/github-workflows/.github/workflows/pullpreview.yml@feature/add-workflows
    with:
      PULLPREVIEW_ADMINS: jheusinger, gael-connan-cybex, holyfabi, lupinitylabs, mszulik
    secrets:
      ENV_VARS: |
        PULLPREVIEW_CONNECTOR_USER_PUBLICKEY="${{ secrets.PULLPREVIEW_CONNECTOR_USER_PUBLICKEY }}"
        PULLPREVIEW_CONNECTOR_PROTECTOR_AUTH_TOKEN_HASH="${{ secrets.PULLPREVIEW_CONNECTOR_PROTECTOR_AUTH_TOKEN_HASH }}"
      PULLPREVIEW_AWS_ACCESS_KEY_ID: ${{ secrets.PULLPREVIEW_AWS_ACCESS_KEY_ID }}
      PULLPREVIEW_AWS_SECRET_ACCESS_KEY: ${{ secrets.PULLPREVIEW_AWS_SECRET_ACCESS_KEY }}

