name: PullPreview
on:
  pull_request:
    types: [ labeled, unlabeled, synchronize, closed, reopened ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read # to fetch code (actions/checkout)
      deployments: write # to delete deployments
      pull-requests: write # to remove labels
      statuses: write # to create commit status
    steps:
      - uses: actions/checkout@v4

      - name: Generate .env file
        env:
          SECRETS_PULLPREVIEW_CONNECTOR_USER_PUBLICKEY: ${{ secrets.PULLPREVIEW_CONNECTOR_USER_PUBLICKEY }}
          SECRETS_PULLPREVIEW_CONNECTOR_PROTECTOR_AUTH_TOKEN_HASH: ${{ secrets.PULLPREVIEW_CONNECTOR_PROTECTOR_AUTH_TOKEN_HASH }}
        run: |
          cp .env.example .env
          echo "APP_ENV=production" >> .env
          echo "APP_DEBUG=false" >> .env
          echo "PULLPREVIEW_CONNECTOR_USER_PUBLICKEY=$SECRETS_PULLPREVIEW_CONNECTOR_USER_PUBLICKEY" >> .env
          echo "PULLPREVIEW_CONNECTOR_PROTECTOR_AUTH_TOKEN_HASH=$SECRETS_PULLPREVIEW_CONNECTOR_PROTECTOR_AUTH_TOKEN_HASH" >> .env

      - uses: pullpreview/action@v5
        with:
          admins: jheusinger, gael-connan-cybex, holyfabi, lupinitylabs, mszulik
          cidrs: "0.0.0.0/0"
          compose_files: docker-compose.pullpreview.yml
          default_port: 80
          instance_type: nano
          ports: 80, 443
        env:
          AWS_ACCESS_KEY_ID: "${{ secrets.PULLPREVIEW_AWS_ACCESS_KEY_ID }}"
          AWS_SECRET_ACCESS_KEY: "${{ secrets.PULLPREVIEW_AWS_SECRET_ACCESS_KEY }}"
          AWS_REGION: "eu-central-1"
